// <auto-generated />
using System;
using Farmers_Market_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Farmers_Market_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260628162811_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Farmers_Market_API.Models.Buyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerType")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Buyers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyerType = 0,
                            Email = "anele@example.com",
                            FullName = "Anele Mokoena",
                            Location = "Cape Town",
                            PhoneNumber = "071-000-0001"
                        },
                        new
                        {
                            Id = 2,
                            BuyerType = 1,
                            Email = "lerato@example.com",
                            FullName = "Lerato Ndlovu",
                            Location = "Johannesburg",
                            PhoneNumber = "071-000-0002"
                        },
                        new
                        {
                            Id = 3,
                            BuyerType = 2,
                            Email = "thabo@example.com",
                            FullName = "Thabo Nkosi",
                            Location = "Durban",
                            PhoneNumber = "071-000-0003"
                        },
                        new
                        {
                            Id = 4,
                            BuyerType = 3,
                            Email = "nandi@example.com",
                            FullName = "Nandi Dlamini",
                            Location = "Pretoria",
                            PhoneNumber = "071-000-0004"
                        },
                        new
                        {
                            Id = 5,
                            BuyerType = 0,
                            Email = "sipho@example.com",
                            FullName = "Sipho Mabaso",
                            Location = "Bloemfontein",
                            PhoneNumber = "071-000-0005"
                        },
                        new
                        {
                            Id = 6,
                            BuyerType = 1,
                            Email = "maya@example.com",
                            FullName = "Maya van Rensburg",
                            Location = "Stellenbosch",
                            PhoneNumber = "071-000-0006"
                        },
                        new
                        {
                            Id = 7,
                            BuyerType = 4,
                            Email = "kuhle@example.com",
                            FullName = "Kuhle Khumalo",
                            Location = "Gqeberha",
                            PhoneNumber = "071-000-0007"
                        },
                        new
                        {
                            Id = 8,
                            BuyerType = 2,
                            Email = "zama@example.com",
                            FullName = "Zama Patel",
                            Location = "Polokwane",
                            PhoneNumber = "071-000-0008"
                        },
                        new
                        {
                            Id = 9,
                            BuyerType = 0,
                            Email = "johan@example.com",
                            FullName = "Johan Botha",
                            Location = "Welkom",
                            PhoneNumber = "071-000-0009"
                        },
                        new
                        {
                            Id = 10,
                            BuyerType = 1,
                            Email = "sonto@example.com",
                            FullName = "Sonto Molefe",
                            Location = "Mbombela",
                            PhoneNumber = "071-000-0010"
                        });
                });

            modelBuilder.Entity("Farmers_Market_API.Models.Farmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Farmers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kobus@example.com",
                            FarmName = "Farm A",
                            FullName = "Kobus",
                            IsVerified = true,
                            Location = "Location A",
                            PhoneNumber = "123-456-7890",
                            Province = "Province A",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Email = "tyrique@example.com",
                            FarmName = "Farm B",
                            FullName = "Tyrique",
                            IsVerified = true,
                            Location = "Location B",
                            PhoneNumber = "098-765-4321",
                            Province = "Province B",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 3,
                            Email = "zandre@example.com",
                            FarmName = "Farm C",
                            FullName = "Zandre",
                            IsVerified = true,
                            Location = "Location C",
                            PhoneNumber = "555-555-5555",
                            Province = "Province C",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Email = "aisha@example.com",
                            FarmName = "Farm D",
                            FullName = "Aisha",
                            IsVerified = true,
                            Location = "Location D",
                            PhoneNumber = "111-222-3333",
                            Province = "Province D",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 5,
                            Email = "bongani@example.com",
                            FarmName = "Farm E",
                            FullName = "Bongani",
                            IsVerified = false,
                            Location = "Location E",
                            PhoneNumber = "222-333-4444",
                            Province = "Province E",
                            Rating = 3.8999999999999999
                        },
                        new
                        {
                            Id = 6,
                            Email = "carmen@example.com",
                            FarmName = "Farm F",
                            FullName = "Carmen",
                            IsVerified = true,
                            Location = "Location F",
                            PhoneNumber = "333-444-5555",
                            Province = "Province F",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 7,
                            Email = "daniel@example.com",
                            FarmName = "Farm G",
                            FullName = "Daniel",
                            IsVerified = true,
                            Location = "Location G",
                            PhoneNumber = "444-555-6666",
                            Province = "Province G",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 8,
                            Email = "elena@example.com",
                            FarmName = "Farm H",
                            FullName = "Elena",
                            IsVerified = false,
                            Location = "Location H",
                            PhoneNumber = "555-666-7777",
                            Province = "Province H",
                            Rating = 3.7999999999999998
                        },
                        new
                        {
                            Id = 9,
                            Email = "farid@example.com",
                            FarmName = "Farm I",
                            FullName = "Farid",
                            IsVerified = true,
                            Location = "Location I",
                            PhoneNumber = "666-777-8888",
                            Province = "Province I",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 10,
                            Email = "grace@example.com",
                            FarmName = "Farm J",
                            FullName = "Grace",
                            IsVerified = true,
                            Location = "Location J",
                            PhoneNumber = "777-888-9999",
                            Province = "Province J",
                            Rating = 4.2999999999999998
                        },
                        new
                        {
                            Id = 11,
                            Email = "hendrik@example.com",
                            FarmName = "Farm K",
                            FullName = "Hendrik",
                            IsVerified = false,
                            Location = "Location K",
                            PhoneNumber = "888-999-0000",
                            Province = "Province K",
                            Rating = 3.7000000000000002
                        },
                        new
                        {
                            Id = 12,
                            Email = "imani@example.com",
                            FarmName = "Farm L",
                            FullName = "Imani",
                            IsVerified = true,
                            Location = "Location L",
                            PhoneNumber = "101-202-3030",
                            Province = "Province L",
                            Rating = 4.4000000000000004
                        },
                        new
                        {
                            Id = 13,
                            Email = "jabulani@example.com",
                            FarmName = "Farm M",
                            FullName = "Jabulani",
                            IsVerified = true,
                            Location = "Location M",
                            PhoneNumber = "121-212-1212",
                            Province = "Province M",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 14,
                            Email = "keisha@example.com",
                            FarmName = "Farm N",
                            FullName = "Keisha",
                            IsVerified = false,
                            Location = "Location N",
                            PhoneNumber = "131-313-1313",
                            Province = "Province N",
                            Rating = 3.6000000000000001
                        },
                        new
                        {
                            Id = 15,
                            Email = "lungile@example.com",
                            FarmName = "Farm O",
                            FullName = "Lungile",
                            IsVerified = true,
                            Location = "Location O",
                            PhoneNumber = "141-414-1414",
                            Province = "Province O",
                            Rating = 4.9000000000000004
                        },
                        new
                        {
                            Id = 16,
                            Email = "mpho@example.com",
                            FarmName = "Farm P",
                            FullName = "Mpho",
                            IsVerified = true,
                            Location = "Location P",
                            PhoneNumber = "151-515-1515",
                            Province = "Province P",
                            Rating = 4.2000000000000002
                        },
                        new
                        {
                            Id = 17,
                            Email = "nokuthula@example.com",
                            FarmName = "Farm Q",
                            FullName = "Nokuthula",
                            IsVerified = false,
                            Location = "Location Q",
                            PhoneNumber = "161-616-1616",
                            Province = "Province Q",
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 18,
                            Email = "omar@example.com",
                            FarmName = "Farm R",
                            FullName = "Omar",
                            IsVerified = true,
                            Location = "Location R",
                            PhoneNumber = "171-717-1717",
                            Province = "Province R",
                            Rating = 4.0999999999999996
                        },
                        new
                        {
                            Id = 19,
                            Email = "palesa@example.com",
                            FarmName = "Farm S",
                            FullName = "Palesa",
                            IsVerified = true,
                            Location = "Location S",
                            PhoneNumber = "181-818-1818",
                            Province = "Province S",
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 20,
                            Email = "quentin@example.com",
                            FarmName = "Farm T",
                            FullName = "Quentin",
                            IsVerified = false,
                            Location = "Location T",
                            PhoneNumber = "191-919-1919",
                            Province = "Province T",
                            Rating = 3.8999999999999999
                        });
                });

            modelBuilder.Entity("Farmers_Market_API.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CollectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FarmerId")
                        .HasColumnType("integer");

                    b.Property<int>("ListingId")
                        .HasColumnType("integer");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("QuantityOrdered")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("ListingId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyerId = 1,
                            FarmerId = 1,
                            ListingId = 1,
                            Notes = "Pickup in the morning",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(6330),
                            QuantityOrdered = 5.0,
                            Status = 0,
                            TotalPrice = 12.5
                        },
                        new
                        {
                            Id = 2,
                            BuyerId = 2,
                            FarmerId = 2,
                            ListingId = 2,
                            Notes = "Please pack separately",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(8945),
                            QuantityOrdered = 3.0,
                            Status = 1,
                            TotalPrice = 9.0
                        },
                        new
                        {
                            Id = 3,
                            BuyerId = 3,
                            FarmerId = 3,
                            ListingId = 3,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(8955),
                            QuantityOrdered = 8.0,
                            Status = 0,
                            TotalPrice = 14.4
                        },
                        new
                        {
                            Id = 4,
                            BuyerId = 4,
                            CollectionDate = new DateTime(2026, 6, 27, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(8956),
                            FarmerId = 1,
                            ListingId = 4,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9053),
                            QuantityOrdered = 2.0,
                            Status = 2,
                            TotalPrice = 4.0
                        },
                        new
                        {
                            Id = 5,
                            BuyerId = 5,
                            FarmerId = 2,
                            ListingId = 5,
                            Notes = "Customer cancelled",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9055),
                            QuantityOrdered = 4.0,
                            Status = 3,
                            TotalPrice = 11.199999999999999
                        },
                        new
                        {
                            Id = 6,
                            BuyerId = 6,
                            FarmerId = 3,
                            ListingId = 6,
                            Notes = "Deliver before noon",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9062),
                            QuantityOrdered = 6.0,
                            Status = 0,
                            TotalPrice = 9.0
                        },
                        new
                        {
                            Id = 7,
                            BuyerId = 7,
                            FarmerId = 1,
                            ListingId = 7,
                            Notes = "Gift packaging requested",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9064),
                            QuantityOrdered = 2.0,
                            Status = 1,
                            TotalPrice = 9.0
                        },
                        new
                        {
                            Id = 8,
                            BuyerId = 8,
                            FarmerId = 2,
                            ListingId = 8,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9065),
                            QuantityOrdered = 5.0,
                            Status = 0,
                            TotalPrice = 16.0
                        },
                        new
                        {
                            Id = 9,
                            BuyerId = 9,
                            CollectionDate = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9067),
                            FarmerId = 3,
                            ListingId = 9,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9068),
                            QuantityOrdered = 10.0,
                            Status = 2,
                            TotalPrice = 12.0
                        },
                        new
                        {
                            Id = 10,
                            BuyerId = 10,
                            FarmerId = 1,
                            ListingId = 10,
                            Notes = "Leave at the front desk",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9070),
                            QuantityOrdered = 3.0,
                            Status = 1,
                            TotalPrice = 6.8999999999999995
                        },
                        new
                        {
                            Id = 11,
                            BuyerId = 1,
                            FarmerId = 2,
                            ListingId = 11,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9072),
                            QuantityOrdered = 4.0,
                            Status = 0,
                            TotalPrice = 7.5999999999999996
                        },
                        new
                        {
                            Id = 12,
                            BuyerId = 2,
                            FarmerId = 3,
                            ListingId = 12,
                            Notes = "Extra careful handling",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9073),
                            QuantityOrdered = 2.0,
                            Status = 1,
                            TotalPrice = 10.0
                        },
                        new
                        {
                            Id = 13,
                            BuyerId = 3,
                            FarmerId = 1,
                            ListingId = 13,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9074),
                            QuantityOrdered = 7.0,
                            Status = 0,
                            TotalPrice = 28.0
                        },
                        new
                        {
                            Id = 14,
                            BuyerId = 4,
                            CollectionDate = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9075),
                            FarmerId = 2,
                            ListingId = 14,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9076),
                            QuantityOrdered = 6.0,
                            Status = 2,
                            TotalPrice = 9.6000000000000014
                        },
                        new
                        {
                            Id = 15,
                            BuyerId = 5,
                            FarmerId = 3,
                            ListingId = 15,
                            Notes = "Order cancelled by buyer",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9077),
                            QuantityOrdered = 9.0,
                            Status = 3,
                            TotalPrice = 31.5
                        },
                        new
                        {
                            Id = 16,
                            BuyerId = 6,
                            FarmerId = 1,
                            ListingId = 16,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9078),
                            QuantityOrdered = 3.0,
                            Status = 0,
                            TotalPrice = 2.7000000000000002
                        },
                        new
                        {
                            Id = 17,
                            BuyerId = 7,
                            FarmerId = 2,
                            ListingId = 17,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9080),
                            QuantityOrdered = 5.0,
                            Status = 1,
                            TotalPrice = 6.0
                        },
                        new
                        {
                            Id = 18,
                            BuyerId = 8,
                            FarmerId = 3,
                            ListingId = 18,
                            Notes = "Urgent pickup",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9082),
                            QuantityOrdered = 4.0,
                            Status = 0,
                            TotalPrice = 3.2000000000000002
                        },
                        new
                        {
                            Id = 19,
                            BuyerId = 9,
                            FarmerId = 1,
                            ListingId = 19,
                            Notes = "",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9103),
                            QuantityOrdered = 8.0,
                            Status = 1,
                            TotalPrice = 8.8000000000000007
                        },
                        new
                        {
                            Id = 20,
                            BuyerId = 10,
                            FarmerId = 2,
                            ListingId = 20,
                            Notes = "Morning delivery",
                            OrderDate = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(9105),
                            QuantityOrdered = 2.0,
                            Status = 0,
                            TotalPrice = 1.8999999999999999
                        });
                });

            modelBuilder.Entity("Farmers_Market_API.Models.ProduceListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateListed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FarmerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<double>("PricePerKg")
                        .HasColumnType("double precision");

                    b.Property<string>("ProduceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("QuantityKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FarmerId");

                    b.ToTable("ProduceListings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 23, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(1163),
                            Description = "Freshly harvested tomatoes.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 18, 18, 28, 11, 179, DateTimeKind.Local).AddTicks(3088),
                            IsAvailable = false,
                            PricePerKg = 2.5,
                            ProduceName = "Tomatoes",
                            QuantityKg = 100.0
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 21, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4867),
                            Description = "Crisp and sweet apples.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 13, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4862),
                            IsAvailable = true,
                            PricePerKg = 3.0,
                            ProduceName = "Apples",
                            QuantityKg = 50.0
                        },
                        new
                        {
                            Id = 3,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 18, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4876),
                            Description = "Organic carrots from our farm.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 8, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4875),
                            IsAvailable = true,
                            PricePerKg = 1.8,
                            ProduceName = "Carrots",
                            QuantityKg = 200.0
                        },
                        new
                        {
                            Id = 4,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4878),
                            Description = "Crisp green lettuce leaves.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 20, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4878),
                            IsAvailable = true,
                            PricePerKg = 2.0,
                            ProduceName = "Lettuce",
                            QuantityKg = 75.0
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 22, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4880),
                            Description = "Juicy navel oranges.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 16, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4879),
                            IsAvailable = false,
                            PricePerKg = 2.7999999999999998,
                            ProduceName = "Oranges",
                            QuantityKg = 60.0
                        },
                        new
                        {
                            Id = 6,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 16, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4889),
                            Description = "Fresh russet potatoes.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 3, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4889),
                            IsAvailable = true,
                            PricePerKg = 1.5,
                            ProduceName = "Potatoes",
                            QuantityKg = 150.0
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4916),
                            Description = "Sweet seasonal strawberries.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 23, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4916),
                            IsAvailable = false,
                            PricePerKg = 4.5,
                            ProduceName = "Strawberries",
                            QuantityKg = 30.0
                        },
                        new
                        {
                            Id = 8,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 24, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4920),
                            Description = "Nutritious broccoli florets.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 21, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4919),
                            IsAvailable = false,
                            PricePerKg = 3.2000000000000002,
                            ProduceName = "Broccoli",
                            QuantityKg = 40.0
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 19, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4922),
                            Description = "Ripe yellow bananas.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 10, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4921),
                            IsAvailable = true,
                            PricePerKg = 1.2,
                            ProduceName = "Bananas",
                            QuantityKg = 80.0
                        },
                        new
                        {
                            Id = 10,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4925),
                            Description = "Fresh baby spinach leaves.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 22, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4925),
                            IsAvailable = true,
                            PricePerKg = 2.2999999999999998,
                            ProduceName = "Spinach",
                            QuantityKg = 55.0
                        },
                        new
                        {
                            Id = 11,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4927),
                            Description = "Crisp garden cucumbers.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 24, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4927),
                            IsAvailable = true,
                            PricePerKg = 1.8999999999999999,
                            ProduceName = "Cucumbers",
                            QuantityKg = 90.0
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 27, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4929),
                            Description = "Plump wild blueberries.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4929),
                            IsAvailable = false,
                            PricePerKg = 5.0,
                            ProduceName = "Blueberries",
                            QuantityKg = 25.0
                        },
                        new
                        {
                            Id = 13,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 13, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4931),
                            Description = "Aromatic garlic bulbs.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 5, 29, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4930),
                            IsAvailable = true,
                            PricePerKg = 4.0,
                            ProduceName = "Garlic",
                            QuantityKg = 15.0
                        },
                        new
                        {
                            Id = 14,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 18, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4933),
                            Description = "Sweet yellow onions.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 8, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4932),
                            IsAvailable = true,
                            PricePerKg = 1.6000000000000001,
                            ProduceName = "Onions",
                            QuantityKg = 120.0
                        },
                        new
                        {
                            Id = 15,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 24, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4934),
                            Description = "Mixed-color bell peppers.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 19, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4934),
                            IsAvailable = true,
                            PricePerKg = 3.5,
                            ProduceName = "Bell Peppers",
                            QuantityKg = 45.0
                        },
                        new
                        {
                            Id = 16,
                            Category = 0,
                            DateListed = new DateTime(2026, 5, 29, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4936),
                            Description = "Large carving pumpkins.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 5, 19, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4936),
                            IsAvailable = false,
                            PricePerKg = 0.90000000000000002,
                            ProduceName = "Pumpkins",
                            QuantityKg = 60.0
                        },
                        new
                        {
                            Id = 17,
                            Category = 2,
                            DateListed = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4938),
                            Description = "Sweet corn on the cob.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 21, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4938),
                            IsAvailable = true,
                            PricePerKg = 1.2,
                            ProduceName = "Corn",
                            QuantityKg = 200.0
                        },
                        new
                        {
                            Id = 18,
                            Category = 2,
                            DateListed = new DateTime(2026, 5, 14, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4949),
                            Description = "Whole wheat grain.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 4, 29, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4949),
                            IsAvailable = true,
                            PricePerKg = 0.80000000000000004,
                            ProduceName = "Wheat (Bulk)",
                            QuantityKg = 500.0
                        },
                        new
                        {
                            Id = 19,
                            Category = 2,
                            DateListed = new DateTime(2026, 6, 3, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4951),
                            Description = "Rolled oats for baking.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 5, 9, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4951),
                            IsAvailable = true,
                            PricePerKg = 1.1000000000000001,
                            ProduceName = "Oats",
                            QuantityKg = 350.0
                        },
                        new
                        {
                            Id = 20,
                            Category = 3,
                            DateListed = new DateTime(2026, 6, 27, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4953),
                            Description = "Fresh whole milk (per liter equivalent).",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4953),
                            IsAvailable = true,
                            PricePerKg = 0.94999999999999996,
                            ProduceName = "Milk",
                            QuantityKg = 200.0
                        },
                        new
                        {
                            Id = 21,
                            Category = 3,
                            DateListed = new DateTime(2026, 6, 21, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4956),
                            Description = "Aged farmhouse cheddar.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 14, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4955),
                            IsAvailable = true,
                            PricePerKg = 8.5,
                            ProduceName = "Cheese",
                            QuantityKg = 20.0
                        },
                        new
                        {
                            Id = 22,
                            Category = 3,
                            DateListed = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4958),
                            Description = "Creamy plain yogurt.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 23, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4957),
                            IsAvailable = true,
                            PricePerKg = 3.2000000000000002,
                            ProduceName = "Yogurt",
                            QuantityKg = 40.0
                        },
                        new
                        {
                            Id = 23,
                            Category = 4,
                            DateListed = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4959),
                            Description = "Pasture-raised whole chicken.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 22, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4959),
                            IsAvailable = true,
                            PricePerKg = 6.5,
                            ProduceName = "Chicken (Whole)",
                            QuantityKg = 35.0
                        },
                        new
                        {
                            Id = 24,
                            Category = 4,
                            DateListed = new DateTime(2026, 6, 24, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4961),
                            Description = "Lean ground beef.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 20, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4961),
                            IsAvailable = true,
                            PricePerKg = 9.0,
                            ProduceName = "Beef (Ground)",
                            QuantityKg = 25.0
                        },
                        new
                        {
                            Id = 25,
                            Category = 4,
                            DateListed = new DateTime(2026, 6, 23, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4963),
                            Description = "Fresh pork chops.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 18, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4963),
                            IsAvailable = true,
                            PricePerKg = 7.2000000000000002,
                            ProduceName = "Pork (Chops)",
                            QuantityKg = 30.0
                        },
                        new
                        {
                            Id = 26,
                            Category = 5,
                            DateListed = new DateTime(2026, 6, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4965),
                            Description = "Free-range brown eggs.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 27, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4964),
                            IsAvailable = true,
                            PricePerKg = 2.5,
                            ProduceName = "Eggs (Dozen)",
                            QuantityKg = 150.0
                        },
                        new
                        {
                            Id = 27,
                            Category = 6,
                            DateListed = new DateTime(2026, 4, 29, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4967),
                            Description = "Raw wildflower honey.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 2, 28, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4966),
                            IsAvailable = true,
                            PricePerKg = 6.0,
                            ProduceName = "Honey",
                            QuantityKg = 18.0
                        },
                        new
                        {
                            Id = 28,
                            Category = 6,
                            DateListed = new DateTime(2026, 6, 27, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4968),
                            Description = "Fresh basil bunches.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4968),
                            IsAvailable = true,
                            PricePerKg = 12.0,
                            ProduceName = "Basil",
                            QuantityKg = 5.0
                        },
                        new
                        {
                            Id = 29,
                            Category = 6,
                            DateListed = new DateTime(2026, 6, 27, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4970),
                            Description = "Curly parsley bunches.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4970),
                            IsAvailable = true,
                            PricePerKg = 4.0,
                            ProduceName = "Parsley",
                            QuantityKg = 12.0
                        },
                        new
                        {
                            Id = 30,
                            Category = 6,
                            DateListed = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4980),
                            Description = "Fresh ginger roots.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 21, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4979),
                            IsAvailable = true,
                            PricePerKg = 9.0,
                            ProduceName = "Ginger",
                            QuantityKg = 8.0
                        },
                        new
                        {
                            Id = 31,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 19, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4982),
                            Description = "Orange-fleshed sweet potatoes.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 10, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4982),
                            IsAvailable = true,
                            PricePerKg = 2.2000000000000002,
                            ProduceName = "Sweet Potatoes",
                            QuantityKg = 80.0
                        },
                        new
                        {
                            Id = 32,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4984),
                            Description = "Fresh curly kale.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 24, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4983),
                            IsAvailable = true,
                            PricePerKg = 3.0,
                            ProduceName = "Kale",
                            QuantityKg = 30.0
                        },
                        new
                        {
                            Id = 33,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4986),
                            Description = "Green zucchinis.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 22, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4985),
                            IsAvailable = true,
                            PricePerKg = 1.7,
                            ProduceName = "Zucchini",
                            QuantityKg = 60.0
                        },
                        new
                        {
                            Id = 34,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 22, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4989),
                            Description = "Juicy Bartlett pears.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 16, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4988),
                            IsAvailable = true,
                            PricePerKg = 2.8999999999999999,
                            ProduceName = "Pears",
                            QuantityKg = 40.0
                        },
                        new
                        {
                            Id = 35,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 24, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4993),
                            Description = "Sweet red plums.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 19, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4992),
                            IsAvailable = false,
                            PricePerKg = 3.2999999999999998,
                            ProduceName = "Plums",
                            QuantityKg = 28.0
                        },
                        new
                        {
                            Id = 36,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 23, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4995),
                            Description = "Seedless table grapes.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 17, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4994),
                            IsAvailable = true,
                            PricePerKg = 4.0999999999999996,
                            ProduceName = "Grapes",
                            QuantityKg = 35.0
                        },
                        new
                        {
                            Id = 37,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4996),
                            Description = "Hass avocados.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 21, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4996),
                            IsAvailable = false,
                            PricePerKg = 2.75,
                            ProduceName = "Avocados",
                            QuantityKg = 22.0
                        },
                        new
                        {
                            Id = 38,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 21, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4998),
                            Description = "Tropical pineapples.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 14, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(4998),
                            IsAvailable = true,
                            PricePerKg = 3.7999999999999998,
                            ProduceName = "Pineapple",
                            QuantityKg = 10.0
                        },
                        new
                        {
                            Id = 39,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 20, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5000),
                            Description = "Green and red cabbages.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 12, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5000),
                            IsAvailable = true,
                            PricePerKg = 1.3999999999999999,
                            ProduceName = "Cabbage",
                            QuantityKg = 48.0
                        },
                        new
                        {
                            Id = 40,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 27, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5002),
                            Description = "Crisp radish bunches.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5001),
                            IsAvailable = true,
                            PricePerKg = 2.0,
                            ProduceName = "Radishes",
                            QuantityKg = 22.0
                        },
                        new
                        {
                            Id = 41,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 21, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5011),
                            Description = "Earthy red beets.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 14, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5003),
                            IsAvailable = true,
                            PricePerKg = 2.5,
                            ProduceName = "Beets",
                            QuantityKg = 26.0
                        },
                        new
                        {
                            Id = 42,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5014),
                            Description = "Crunchy celery stalks.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 23, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5013),
                            IsAvailable = true,
                            PricePerKg = 1.8,
                            ProduceName = "Celery",
                            QuantityKg = 20.0
                        },
                        new
                        {
                            Id = 43,
                            Category = 0,
                            DateListed = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5015),
                            Description = "Fresh snap beans.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 22, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5015),
                            IsAvailable = true,
                            PricePerKg = 3.1000000000000001,
                            ProduceName = "Green Beans",
                            QuantityKg = 34.0
                        },
                        new
                        {
                            Id = 44,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 24, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5017),
                            Description = "Juicy summer peaches.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 20, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5017),
                            IsAvailable = true,
                            PricePerKg = 3.6000000000000001,
                            ProduceName = "Peaches",
                            QuantityKg = 27.0
                        },
                        new
                        {
                            Id = 45,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 23, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5019),
                            Description = "Sweet nectarines.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2026, 6, 18, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5019),
                            IsAvailable = false,
                            PricePerKg = 3.7000000000000002,
                            ProduceName = "Nectarines",
                            QuantityKg = 18.0
                        },
                        new
                        {
                            Id = 46,
                            Category = 1,
                            DateListed = new DateTime(2026, 6, 24, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5021),
                            Description = "Sun-ripened apricots.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 6, 19, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5020),
                            IsAvailable = true,
                            PricePerKg = 4.2000000000000002,
                            ProduceName = "Apricots",
                            QuantityKg = 12.0
                        },
                        new
                        {
                            Id = 47,
                            Category = 6,
                            DateListed = new DateTime(2026, 6, 27, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5023),
                            Description = "Bunches of mixed culinary herbs.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 26, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5022),
                            IsAvailable = true,
                            PricePerKg = 10.0,
                            ProduceName = "Mixed Herbs",
                            QuantityKg = 6.0
                        },
                        new
                        {
                            Id = 48,
                            Category = 6,
                            DateListed = new DateTime(2026, 3, 20, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5024),
                            Description = "Locally grown almonds.",
                            FarmerId = 3,
                            HarvestDate = new DateTime(2025, 12, 10, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5024),
                            IsAvailable = true,
                            PricePerKg = 12.5,
                            ProduceName = "Almonds (Shelled)",
                            QuantityKg = 14.0
                        },
                        new
                        {
                            Id = 49,
                            Category = 2,
                            DateListed = new DateTime(2026, 5, 14, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5026),
                            Description = "Dry lentils for cooking.",
                            FarmerId = 1,
                            HarvestDate = new DateTime(2026, 3, 30, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5026),
                            IsAvailable = true,
                            PricePerKg = 1.6000000000000001,
                            ProduceName = "Lentils (Bulk)",
                            QuantityKg = 220.0
                        },
                        new
                        {
                            Id = 50,
                            Category = 6,
                            DateListed = new DateTime(2026, 6, 27, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5028),
                            Description = "Freshly made soybean tofu.",
                            FarmerId = 2,
                            HarvestDate = new DateTime(2026, 6, 25, 18, 28, 11, 180, DateTimeKind.Local).AddTicks(5028),
                            IsAvailable = true,
                            PricePerKg = 4.5,
                            ProduceName = "Tofu (Fresh)",
                            QuantityKg = 30.0
                        });
                });

            modelBuilder.Entity("Farmers_Market_API.Models.Order", b =>
                {
                    b.HasOne("Farmers_Market_API.Models.Buyer", null)
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Farmers_Market_API.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Farmers_Market_API.Models.ProduceListing", null)
                        .WithMany()
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Farmers_Market_API.Models.ProduceListing", b =>
                {
                    b.HasOne("Farmers_Market_API.Models.Farmer", null)
                        .WithMany()
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
